return {
  controls = {
    cancel = {
      id = "commands.cancel",
      keys = { "<Esc>" },
      hidden = true,
      label = "Cancel",
    },
    help = {
      id = "commands.help",
      keys = { "?" },
      group = "General",
      label = "Help",
    },
  },
  commands = {
    {
      kind = "menu",
      id = "revision.abandon",
      keys = { "a" },
      group = "Commands",
      label = "Abandon",
      children = {
        {
          kind = "action",
          id = "revision.abandon.selection",
          keys = { "a" },
          label = "Selection",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.abandon.retain_bookmarks",
          keys = { "b" },
          label = "Selection (retain bookmarks)",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.abandon.restore_descendants",
          keys = { "d" },
          label = "Selection (restore descendants)",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
      },
    },
    {
      kind = "menu",
      id = "revision.edit",
      keys = { "e" },
      group = "Commands",
      label = "Edit",
      children = {
        {
          kind = "action",
          id = "revision.edit.selection",
          keys = { "e" },
          label = "Selection",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.edit.target",
          keys = { "/" },
          label = "Target",
          requires = { "repository" },
          unavailable = "Requires a repository",
        },
      },
    },
    {
      kind = "menu",
      id = "git",
      keys = { "g" },
      group = "Commands",
      label = "Git",
      children = {
        {
          kind = "menu",
          id = "git.fetch",
          keys = { "f" },
          group = "Git",
          label = "Fetch",
          children = {
            {
              kind = "action",
              id = "git.fetch.default",
              keys = { "f" },
              group = "Git fetch",
              label = "Default",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.fetch.all_remotes",
              keys = { "a" },
              group = "Git fetch",
              label = "All remotes",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.fetch.tracked",
              keys = { "t" },
              group = "Git fetch",
              label = "Tracked bookmarks and tags",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.fetch.branch",
              keys = { "b" },
              group = "Git fetch",
              label = "Branch by name",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.fetch.remote",
              keys = { "r" },
              group = "Git fetch",
              label = "Remote by name",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
          },
        },
        {
          kind = "menu",
          id = "git.push",
          keys = { "p" },
          group = "Git",
          label = "Push",
          children = {
            {
              kind = "action",
              id = "git.push.default",
              keys = { "p" },
              group = "Git push",
              label = "Default",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.push.all",
              keys = { "a" },
              group = "Git push",
              label = "All bookmarks and tags",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.push.revision",
              keys = { "r" },
              group = "Git push",
              label = "Bookmarks and tags at selection",
              requires = { "commit" },
              unavailable = "Requires a commit",
            },
            {
              kind = "action",
              id = "git.push.tracked",
              keys = { "t" },
              group = "Git push",
              label = "Tracked bookmarks and tags",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.push.deleted",
              keys = { "d" },
              group = "Git push",
              label = "Deleted bookmarks and tags",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
            {
              kind = "action",
              id = "git.push.change",
              keys = { "c" },
              group = "Git push",
              label = "New bookmark for selection",
              requires = { "commit" },
              unavailable = "Requires a commit",
            },
            {
              kind = "action",
              id = "git.push.named",
              keys = { "n" },
              group = "Git push",
              label = "New named bookmark for selection",
              requires = { "commit" },
              unavailable = "Requires a commit",
            },
            {
              kind = "action",
              id = "git.push.bookmark",
              keys = { "b" },
              group = "Git push",
              label = "Bookmark by name",
              requires = { "repository" },
              unavailable = "Requires a repository",
            },
          },
        },
      },
    },
    {
      kind = "menu",
      id = "revision.new",
      keys = { "n" },
      group = "Commands",
      label = "New",
      children = {
        {
          kind = "action",
          id = "revision.new.after",
          keys = { "n" },
          label = "After selection",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.new.insert_after",
          keys = { "a" },
          label = "After selection (rebase children)",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.new.insert_before",
          keys = { "b" },
          label = "Before selection (rebase children)",
          requires = { "commit" },
          unavailable = "Requires a commit",
        },
        {
          kind = "action",
          id = "revision.new.trunk",
          keys = { "m" },
          label = "After trunk",
          requires = { "repository" },
          unavailable = "Requires a repository",
        },
        {
          kind = "action",
          id = "revision.new.trunk_sync",
          keys = { "M" },
          label = "After trunk (sync)",
          requires = { "repository" },
          unavailable = "Requires a repository",
        },
        {
          kind = "action",
          id = "revision.new.target",
          keys = { "/" },
          label = "After target",
          requires = { "repository" },
          unavailable = "Requires a repository",
        },
        {
          kind = "action",
          id = "revision.new.revsets",
          keys = { "r" },
          label = "After revsets",
          requires = { "repository" },
          unavailable = "Requires a repository",
        },
      },
    },
    {
      kind = "menu",
      id = "operation.undo_redo",
      keys = { "u" },
      group = "Commands",
      label = "Undo/Redo",
      children = {
        {
          kind = "action",
          id = "operation.undo",
          keys = { "u" },
          label = "Undo last operation",
        },
        {
          kind = "action",
          id = "operation.redo",
          keys = { "r" },
          label = "Redo last operation",
        },
      },
    },
    {
      kind = "action",
      id = "options.ignore_immutable",
      keys = { "I" },
      group = "General",
      label = "Toggle --ignore-immutable",
      available_during_session = true,
      preserve_session = true,
    },
    {
      kind = "action",
      id = "view.close",
      keys = { "q" },
      group = "General",
      label = "Close",
      available_during_session = true,
    },
    {
      kind = "action",
      id = "view.open",
      keys = { "<CR>" },
      group = "General",
      label = "Open",
      requires = { "file" },
      unavailable = "Requires a file",
    },
    {
      kind = "action",
      id = "view.refresh",
      keys = { "<C-r>", "<BS>" },
      group = "General",
      label = "Refresh",
      available_during_session = true,
    },
    {
      kind = "action",
      id = "view.toggle",
      keys = { "<Tab>", "za" },
      group = "General",
      label = "Toggle fold",
      requires = { "foldable" },
      unavailable = "Requires a fold",
      available_during_session = true,
      preserve_session = true,
    },
    {
      kind = "action",
      id = "view.right_click",
      keys = { "<RightMouse>", "<2-RightMouse>", "<3-RightMouse>", "<4-RightMouse>" },
      hidden = true,
      label = "Select and toggle fold",
      available_during_session = true,
      preserve_session = true,
    },
  },
}
